#!/usr/bin/env python3
import os
import re
import subprocess
import sys
from pathlib import Path

import gi

gi.require_version('Notify', '0.7')
from gi.repository import Notify

# This file is shared by all the scripts I use which display notifications,
# so that they replace each other's notifications.
NOTIFICATION_ID_FILE = Path(f"/run/user/{os.getuid()}/notification-id")

PYTHON_STACKTRACE_REGEX = re.compile(r'.*File "([^"]+)", line (\d+), in .*')
GIT_DIFF_PATH_REGEX = re.compile(r'^[ab]/(.+)$')
JIRA_ISSUE_REGEX = re.compile(r'[A-Z]+-\d+')

# Add $HOME/.local/bin to the PATH
os.environ['PATH'] = f"{os.environ['PATH']}:{Path.home()}/.local/bin"

ALT = len(sys.argv) > 1 and sys.argv[1] == "--alt"

class Editor:
    def open(self, path, line_number=None):
        raise NotImplementedError


class IntelliJ(Editor):
    def open(self, path, line_number=None):
        command = ["idea"]
        real_path = Path(path)

        if not real_path.exists():
            notify("File not found", str(path))
            return

        if line_number:
            command = command + ['--line', line_number, str(real_path)]
        else:
            command = command + [str(real_path)]
        notify("Opening file in IntelliJ", str(real_path))
        print(f"Command: {' '.join(command)}", file=sys.stderr)
        subprocess.run(command)


class VSCode(Editor):
    def __init__(self):
        self.command = ["code"]
        self.name = "VS Code"

    def open(self, path, line_number=None):
        real_path = Path(path)

        if not real_path.exists():
            notify("File not found", str(path))
            return

        if line_number:
            command = self.command + ['--goto', f"{real_path}:{line_number}"]
        else:
            command = self.command + [str(real_path)]
        notify(f"Opening file in {self.name}", str(real_path))
        print(f"Command: {' '.join(command)}", file=sys.stderr)
        subprocess.run(command)


class Cursor(VSCode):
    def __init__(self):
        super().__init__()
        self.command = ["cursor"]
        self.name = "Cursor"

if ALT:
    EDITOR = Cursor()
else:
    EDITOR = IntelliJ()


def notify(title, body):
    if NOTIFICATION_ID_FILE.exists():
        id_ = int(NOTIFICATION_ID_FILE.read_text().strip())
    else:
        id_ = 0

    notification = Notify.Notification(
        summary=title,
        body=body,
        id=id_,
    )
    try:
        notification.show()
    except gi.repository.GLib.Error as e:
        if "Invalid notification ID" in str(e):
            # Delete the notification file and try again
            NOTIFICATION_ID_FILE.unlink()
            notify(title, body)
            return
        raise

    Path(NOTIFICATION_ID_FILE).write_text(str(notification.props.id))


def main():
    Notify.init("local.magic-shortcut")

    path, line_number = None, None

    # Get the clipboard content via wl-clipboard (this assumes Wayland)
    clipboard_content = subprocess.run(
        ["wl-paste"],
        stdout=subprocess.PIPE,
        text=True,
    ).stdout.strip()

    if not clipboard_content:
        # Show a notification if the clipboard is empty
        notify("Clipboard is empty", "Nothing to do")
        return

    # If the clipboard content is a URL, open it in the browser
    if clipboard_content.startswith("http://") or clipboard_content.startswith("https://"):
        notify("Opening URL in browser", clipboard_content)
        # If the default browser is Firefox, we can use `firefox --new-window`
        # to open the URL in a new window. Otherwise, we just use `xdg-open`.
        if subprocess.check_output(["xdg-settings", "get", "default-web-browser"], text=True).strip().startswith("firefox"):
            subprocess.run(["firefox", "--new-window", clipboard_content])
        else:
            subprocess.run(["xdg-open", clipboard_content])
        return

    # If the clipboard content is a Jira issue key, open the issue in the browser
    match = JIRA_ISSUE_REGEX.match(clipboard_content)
    if match:
        issue_key = match.group(0)
        print(f"Opening Jira issue {issue_key}", file=sys.stderr)
        subprocess.run(["xdg-open", f"https://warthogs.atlassian.net/browse/{issue_key}"])
        return

    # If the clipboard content is a Python stack trace, open the files in IntelliJ
    match = PYTHON_STACKTRACE_REGEX.match(clipboard_content)
    if match:
        path = match.group(1)
        line_number = match.group(2)
        print(f"Opening Python stacktrace {path}", file=sys.stderr)

    # If the clipboard content is a git diff, open the files in IntelliJ
    match = GIT_DIFF_PATH_REGEX.match(clipboard_content)
    if match:
        path = match.group(1)
        print(f"Opening git diff {path}", file=sys.stderr)

    # If the clipboard content is a path to an existing file (optionally
    # with a line number), open the file in IntelliJ
    if not path and ':' in clipboard_content:
        # We want to support both "path/to/file:line_number" and
        # "path/to/file:line_number:" (the latter is shown by `git diff`),
        # so we ignore everything after the second colon.
        parts = clipboard_content.split(':')
        path, line_number = parts[0], parts[1]
    elif not path:
        path, line_number = clipboard_content, None

    path = Path(path)
    if path.exists():
        print(f"Trying {path}", file=sys.stderr)
        EDITOR.open(path, line_number)
        return

    # If the clipboard content is a relative path below the authd
    # or authd-oidc-brokers project directories, open the file in
    # IntelliJ
    if not path.is_absolute():
        for project in ["authd", "authd-oidc-brokers"]:
            project_path = Path(f"~/projects/{project}").expanduser()
            absolute_path = project_path / path
            if absolute_path.exists():
                print(f"Trying {absolute_path}", file=sys.stderr)
                EDITOR.open(absolute_path, line_number)
                return
            # If the path starts with the project directory, remove that part
            if path.parts[0] == project:
                absolute_path = project_path / Path(*path.parts[1:])
                if absolute_path.exists():
                    print(f"Trying {absolute_path}", file=sys.stderr)
                    EDITOR.open(absolute_path, line_number)
                    return

    # Show a notification
    notify("Clipboard content not recognized", clipboard_content)


if __name__ == '__main__':
    main()
