#!/usr/bin/env python3
import os
import re
import subprocess
import sys
from pathlib import Path

import gi

gi.require_version('Notify', '0.7')
from gi.repository import Notify

# This file is shared by all the scripts I use which display notifications,
# so that they replace each other's notifications.
NOTIFICATION_ID_FILE = Path(f"/run/user/{os.getuid()}/notification-id")

INTELLIJ_COMMAND = ["idea.sh"]

PYTHON_STACKTRACE_REGEX = re.compile(r'.*File "([^"]+)", line (\d+), in .*')
GIT_DIFF_PATH_REGEX = re.compile(r'^[ab]/(.+)$')


def notify(title, body):
    if NOTIFICATION_ID_FILE.exists():
        id_ = int(NOTIFICATION_ID_FILE.read_text().strip())
    else:
        id_ = 0

    notification = Notify.Notification(
        summary=title,
        body=body,
        id=id_,
    )
    notification.show()

    Path(NOTIFICATION_ID_FILE).write_text(str(notification.props.id))


def open_in_intellij(path, line_number=None):
    real_path = Path(path)

    if not real_path.exists():
        notify("File not found", str(path))
        return

    if line_number:
        command = INTELLIJ_COMMAND + ['--line', line_number, str(real_path)]
    else:
        command = INTELLIJ_COMMAND + [str(real_path)]
    notify("Opening file in IntelliJ", str(real_path))
    print(f"Command: {' '.join(command)}", file=sys.stderr)
    subprocess.run(command)


def main():
    Notify.init("local.magic-shortcut")

    # Get the clipboard content via wl-clipboard (this assumes Wayland)
    clipboard_content = subprocess.run(
        ["wl-paste"],
        stdout=subprocess.PIPE,
        text=True,
    ).stdout.strip()

    if not clipboard_content:
        # Show a notification if the clipboard is empty
        notify("Clipboard is empty", "Nothing to do")
        return

    # If the clipboard content is a Python stack trace, open the files in IntelliJ
    match = PYTHON_STACKTRACE_REGEX.match(clipboard_content)
    if match:
        path = match.group(1)
        line_number = match.group(2)
        print(f"Opening Python stacktrace {path}", file=sys.stderr)
        open_in_intellij(path, line_number)
        return

    # If the clipboard content is a git diff, open the files in IntelliJ
    match = GIT_DIFF_PATH_REGEX.match(clipboard_content)
    if match:
        path = match.group(1)
        print(f"Opening git diff {path}", file=sys.stderr)
        open_in_intellij(path)
        return

    # If the clipboard content is a path to an existing file (optionally
    # with a line number), open the file in IntelliJ
    if ':' in clipboard_content:
        path, line_number = clipboard_content.split(':')
    else:
        path, line_number = clipboard_content, None
    path = Path(path)
    if path.exists():
        print(f"Trying {path}", file=sys.stderr)
        open_in_intellij(path, line_number)
        return

    # Show a notification
    notify("Clipboard content not recognized", clipboard_content)


if __name__ == '__main__':
    main()
